-- =============================================================
-- 09 · Observability and Data Flywheel · Table DDL
--
-- New tables introduced in this chapter:
--   review_queue
--     Review queue containing normalized and deduplicated knowledge gaps.
--
--   eval_runs
--     Stores the result of each automated evaluation run so that
--     metric trends can be tracked over time.
--
-- Two columns are also added to low_confidence_questions:
--
--   matched_review_id
--     Records which deduplicated knowledge gap this original question
--     was merged into.
--
--   retrieved_chunks
--     Stores a snapshot of the retrieved chunks at the time the
--     low-confidence question was recorded, so reviewers can inspect
--     the evidence on the review page.
--
-- Creation order:
--   1. CREATE review_queue
--   2. ALTER low_confidence_questions and add the foreign key
--      referencing review_queue.
-- =============================================================

-- Ensure ENUM values, DEFAULT values, and COMMENT text are parsed as utf8mb4.
-- Otherwise, a MySQL client using latin1 by default may double-encode
-- non-ASCII text and corrupt stored values.
SET NAMES utf8mb4;


-- Review queue:
-- One row represents one deduplicated knowledge gap.
-- When a duplicate is found, occurrence_count is incremented instead
-- of creating a new row.
CREATE TABLE review_queue (
  id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT 'Primary key of the knowledge gap; also returned as matched_question_id when deduplication finds a match',

  normalized_question VARCHAR(512)    NOT NULL
    COMMENT 'Normalized FAQ-style question',

  ai_suggested_answer TEXT            NULL
    COMMENT 'Example answer generated by the model for reviewer reference',

  occurrence_count    INT UNSIGNED    NOT NULL DEFAULT 1
    COMMENT 'Number of occurrences; incremented when deduplication finds a match, with higher counts indicating higher review priority',

  review_status       ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending'
    COMMENT 'Manual review status',

  approved_answer     TEXT            NULL
    COMMENT 'Reviewer-approved answer; written back to the knowledge base through the existing 03 ingestion flow after approval',

  created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
    COMMENT 'Time when the knowledge gap was first added to the queue',

  updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    COMMENT 'Last updated time',

  PRIMARY KEY (id),
  KEY idx_review_status (review_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Data flywheel review queue';


-- Evaluation runs:
-- One row represents one completed evaluation pipeline run.
-- Individual metric scores are stored in the metrics JSON column;
-- plotting them over time provides the evaluation trend.
CREATE TABLE eval_runs (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT 'Primary key of the evaluation run',

  triggered_by ENUM('scheduled','manual') NOT NULL DEFAULT 'scheduled'
    COMMENT 'How this evaluation run was triggered: scheduled task or manual run after a change',

  dataset_size INT UNSIGNED    NOT NULL
    COMMENT 'Number of evaluation samples processed in this run',

  metrics      JSON            NOT NULL
    COMMENT 'Evaluation metrics, for example {"recall_at_k":0.82,"mrr":0.71,"faithfulness":0.90}',

  created_at   DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
    COMMENT 'Time when the completed evaluation result was stored',

  PRIMARY KEY (id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Automated evaluation pipeline run results';


-- Record the deduplication destination for each original low-confidence question.
--
-- After normalization and deduplication, matched_review_id points to
-- the corresponding knowledge-gap row in review_queue.
-- NULL means that the question has not yet been processed.
--
-- Also store a snapshot of the retrieved chunks captured when the
-- low-confidence question was recorded. The snapshot contains the
-- original text and scores of the top retrieved chunks and is shown
-- on the review page.
--
-- Entries that did not go through retrieval may leave this field NULL.
ALTER TABLE low_confidence_questions
  ADD COLUMN retrieved_chunks JSON NULL
    COMMENT 'Snapshot of the top retrieved chunks when the question entered the low-confidence pool, including original text and scores; displayed on the review page; NULL when retrieval was not performed'
    AFTER reason,

  ADD COLUMN matched_review_id BIGINT UNSIGNED NULL
    COMMENT 'Deduplicated knowledge gap this question was merged into; references review_queue.id'
    AFTER retrieved_chunks,

  ADD KEY idx_matched_review_id (matched_review_id),

  ADD CONSTRAINT fk_lcq_review
    FOREIGN KEY (matched_review_id)
    REFERENCES review_queue (id)
    ON DELETE SET NULL;
